project:
  type: default
  output-dir: _output

format:
  revealjs:
    theme: [default, custom.scss]
    embed-resources: true
    pdf-separate-fragments: false
    
    # Accessibility
    navigation-mode: linear
    hash-type: number
    
    # Navigation
    slide-number: true
    controls: true
    progress: true
    
    # Appearance
    transition: fade
    transition-speed: fast
    center: false
    
    # Code
    code-overflow: wrap
    highlight-style: a11y-dark

    # Chalkboard
    chalkboard: false
    chalkboard-theme: dark
